export default function () {
    return [
  {
    "Player": "Davon Reed",
    "Position": "Guard",
    "Games Played": 31,
    "Average Minutes Played": 35.3,
    "PPG": 15.2,
    "RPG": 4.8,
    "APG": 2.5,
    "FGM": 154,
    "FGA": 354,
    "FG%": 43.5,
    "FTM": 88,
    "FTA": 106,
    "FT%": 83,
    "3PTM": 76,
    "3PA": 188,
    "3P%": 40.4
  },
  {
    "Player": "Ja'Quan Newton",
    "Position": "Guard",
    "Games Played": 28,
    "Average Minutes Played": 31.5,
    "PPG": 13.8,
    "RPG": 3.6,
    "APG": 3.4,
    "FGM": 144,
    "FGA": 316,
    "FG%": 45.6,
    "FTM": 86,
    "FTA": 121,
    "FT%": 71.1,
    "3PTM": 11,
    "3PA": 39,
    "3P%": 28.2
  },
  {
    "Player": "Bruce Brown",
    "Position": "Guard",
    "Games Played": 31,
    "Average Minutes Played": 31.8,
    "PPG": 11.6,
    "RPG": 5.8,
    "APG": 3.2,
    "FGM": 122,
    "FGA": 273,
    "FG%": 44.7,
    "FTM": 84,
    "FTA": 113,
    "FT%": 74.3,
    "3PTM": 31,
    "3PA": 89,
    "3P%": 34.8
  },
  {
    "Player": "Kamari Murphy",
    "Position": "Forward",
    "Games Played": 31,
    "Average Minutes Played": 29.7,
    "PPG": 7.4,
    "RPG": 7.5,
    "APG": 0.6,
    "FGM": 94,
    "FGA": 177,
    "FG%": 53.1,
    "FTM": 40,
    "FTA": 65,
    "FT%": 61.5,
    "3PTM": 0,
    "3PA": 1,
    "3P%": 0
  },
  {
    "Player": "Anthony Lawrence Jr.",
    "Position": "Guard",
    "Games Played": 31,
    "Average Minutes Played": 25.9,
    "PPG": 6.9,
    "RPG": 3.8,
    "APG": 1.8,
    "FGM": 69,
    "FGA": 162,
    "FG%": 42.6,
    "FTM": 45,
    "FTA": 62,
    "FT%": 72.6,
    "3PTM": 32,
    "3PA": 89,
    "3P%": 36
  },
  {
    "Player": "Dejan Vasiljevic",
    "Position": "Guard",
    "Games Played": 31,
    "Average Minutes Played": 17.5,
    "PPG": 6.1,
    "RPG": 1.3,
    "APG": 0.4,
    "FGM": 62,
    "FGA": 170,
    "FG%": 36.5,
    "FTM": 15,
    "FTA": 19,
    "FT%": 78.9,
    "3PTM": 50,
    "3PA": 138,
    "3P%": 36.2
  },
  {
    "Player": "Dewan Huell",
    "Position": "Forward",
    "Games Played": 30,
    "Average Minutes Played": 17.9,
    "PPG": 5.9,
    "RPG": 3.2,
    "APG": 0.2,
    "FGM": 73,
    "FGA": 139,
    "FG%": 52.5,
    "FTM": 32,
    "FTA": 49,
    "FT%": 65.3,
    "3PTM": 0,
    "3PA": 2,
    "3P%": 0
  },
  {
    "Player": "Ebuka Izundu",
    "Position": "Center",
    "Games Played": 30,
    "Average Minutes Played": 13,
    "PPG": 4.3,
    "RPG": 3,
    "APG": 0.2,
    "FGM": 51,
    "FGA": 91,
    "FG%": 56,
    "FTM": 26,
    "FTA": 38,
    "FT%": 68.4,
    "3PTM": 0,
    "3PA": 0,
    "3P%": 0
  },
  {
    "Player": "Rodney Miller",
    "Position": "Center",
    "Games Played": 13,
    "Average Minutes Played": 3.7,
    "PPG": 0.9,
    "RPG": 0.6,
    "APG": 0,
    "FGM": 4,
    "FGA": 8,
    "FG%": 50,
    "FTM": 4,
    "FTA": 9,
    "FT%": 44.4,
    "3PTM": 0,
    "3PA": 0,
    "3P%": 0
  },
  {
    "Player": "Mike Robinson",
    "Position": "Guard",
    "Games Played": 7,
    "Average Minutes Played": 2.1,
    "PPG": 0.1,
    "RPG": 0.1,
    "APG": 0,
    "FGM": 0,
    "FGA": 4,
    "FG%": 0,
    "FTM": 1,
    "FTA": 2,
    "FT%": 50,
    "3PTM": 0,
    "3PA": 3,
    "3P%": 0
  },
  {
    "Player": "Chris Stowell",
    "Position": "Forward",
    "Games Played": 5,
    "Average Minutes Played": 1.8,
    "PPG": 0,
    "RPG": 0.4,
    "APG": 0,
    "FGM": 0,
    "FGA": 1,
    "FG%": 0,
    "FTM": 0,
    "FTA": 0,
    "FT%": 0,
    "3PTM": 0,
    "3PA": 1,
    "3P%": 0
  }
];
}